AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Lambda hola mundo.
Parameters:
  Env:
    Type: String
    Default: dev

Resources:
  helloworld:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      AutoPublishAlias: live
      CodeUri: .
      Description: Lambda hola mundo.
      MemorySize: 128
      Timeout: 3
      Environment:
        Variables:
          User: myuser
          Env: !Ref Env
          Region: !Ref AWS::Region